{{- $secretName := ( printf "%v-tls-0-ixcert-%v-%v" $.Chart.Name $.Values.ingress.scaleCert $.Release.Revision ) -}}
{{- $cert := get $.Values.ixCertificates ( $.Values.ingress.scaleCert | toString ) -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    "traefik.ingress.kubernetes.io/router.entrypoints": "websecure"
    "traefik.ingress.kubernetes.io/router.middlewares": "ix-traefik-chain-basic@kubernetescrd"

spec:
  tls:
  - secretName: {{ $secretName }}
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 8086

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.certificate | toString | b64enc | quote }}
  tls.key: {{ $cert.privatekey | toString | b64enc | quote }}
